// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AskForTask: typeof import('./src/components/AskForTask.vue')['default']
    FooterSummary: typeof import('./src/components/FooterSummary.vue')['default']
    'ICarbon:addFilled': typeof import('~icons/carbon/add-filled')['default']
    'ICarbon:moon': typeof import('~icons/carbon/moon')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IIc:roundCancel': typeof import('~icons/ic/round-cancel')['default']
    'IMdi:databaseCheckOutline': typeof import('~icons/mdi/database-check-outline')['default']
    'IMdi:databaseRemoveOutline': typeof import('~icons/mdi/database-remove-outline')['default']
    ListTodos: typeof import('./src/components/ListTodos.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
