// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AskForTask: typeof import('./src/components/AskForTask.vue')['default']
    FooterSummary: typeof import('./src/components/FooterSummary.vue')['default']
    ListTodos: typeof import('./src/components/ListTodos.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}

export { }
