/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
var n=function(){return(n=Object.assign||function(n){for(var t,e=1,r=arguments.length;e<r;e++)for(var o in t=arguments[e])Object.prototype.hasOwnProperty.call(t,o)&&(n[o]=t[o]);return n}).apply(this,arguments)};function t(n,t){void 0===t&&(t=!1);var e=function(){var n=new Int8Array(1);window.crypto.getRandomValues(n);var t=new Uint8Array(Math.max(16,Math.abs(n[0])));return window.crypto.getRandomValues(t),t.join("")}();return Object.defineProperty(window,e,{value:function(r){return t&&Reflect.deleteProperty(window,e),null==n?void 0:n(r)},writable:!1,configurable:!0}),e}function e(e,r){return void 0===r&&(r={}),function(n,t,e,r){return new(e||(e=Promise))((function(o,i){function u(n){try{l(r.next(n))}catch(n){i(n)}}function a(n){try{l(r.throw(n))}catch(n){i(n)}}function l(n){var t;n.done?o(n.value):(t=n.value,t instanceof e?t:new e((function(n){n(t)}))).then(u,a)}l((r=r.apply(n,t||[])).next())}))}(this,void 0,void 0,(function(){return function(n,t){var e,r,o,i,u={label:0,sent:function(){if(1&o[0])throw o[1];return o[1]},trys:[],ops:[]};return i={next:a(0),throw:a(1),return:a(2)},"function"==typeof Symbol&&(i[Symbol.iterator]=function(){return this}),i;function a(i){return function(a){return function(i){if(e)throw new TypeError("Generator is already executing.");for(;u;)try{if(e=1,r&&(o=2&i[0]?r.return:i[0]?r.throw||((o=r.return)&&o.call(r),0):r.next)&&!(o=o.call(r,i[1])).done)return o;switch(r=0,o&&(i=[2&i[0],o.value]),i[0]){case 0:case 1:o=i;break;case 4:return u.label++,{value:i[1],done:!1};case 5:u.label++,r=i[1],i=[0];continue;case 7:i=u.ops.pop(),u.trys.pop();continue;default:if(!((o=(o=u.trys).length>0&&o[o.length-1])||6!==i[0]&&2!==i[0])){u=0;continue}if(3===i[0]&&(!o||i[1]>o[0]&&i[1]<o[3])){u.label=i[1];break}if(6===i[0]&&u.label<o[1]){u.label=o[1],o=i;break}if(o&&u.label<o[2]){u.label=o[2],u.ops.push(i);break}o[2]&&u.ops.pop(),u.trys.pop();continue}i=t.call(n,u)}catch(n){i=[6,n],r=0}finally{e=o=0}if(5&i[0])throw i[1];return{value:i[0]?i[1]:void 0,done:!0}}([i,a])}}}(this,(function(o){return[2,new Promise((function(o,i){var u=t((function(n){o(n),Reflect.deleteProperty(window,a)}),!0),a=t((function(n){i(n),Reflect.deleteProperty(window,u)}),!0);window.rpc.notify(e,n({__invokeKey:__TAURI_INVOKE_KEY__,callback:u,error:a},r))}))]}))}))}Object.freeze({__proto__:null,transformCallback:t,invoke:e,convertFileSrc:function(n){return navigator.userAgent.includes("Windows")?"https://asset.localhost/"+n:"asset://"+n}});var r=function(){function n(n){this.path=n}return n.load=function(t){e("plugin:sql|sqlx_load",{db:t}).then((function(){return new n(t)}))},n.get=function(t){return new n(t)},n.prototype.execute=function(n){return e("plugin:sql|sqlx_execute",{db:this.path,query:n})},n.prototype.select=function(n){return e("plugin:sql|sqlx_select",{db:this.path,query:n})},n}();export default r;
